apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-app-deploy
  labels:
    app: banking-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: banking-app
  template:
    metadata:
      labels:
        app: banking-app
    spec:
      containers:
      - name: banking-app-container
        image: ramadev726/banking-app
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: banking-app-np-service
  labels:
    app: banking-app
spec:
  selector:
    app: banking-app

  type: NodePort
  ports:
  - nodePort: 32222
    port: 8081
    targetPort: 8081
